JellyDiary/JellyDiary_FE

src/pages/WritePage/WritePageDesc/WritePageImg/WritePageImg.styles.ts
src/pages/WritePage/WritePageDesc/WritePageImg/WritePageImg.tsx

[JD-63]
이미지 한 장만 업로드 -> 이미지 여러장 업로드 및 미리보기
[JD-63]: https://ttokttak.atlassian.net/browse/JD-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-63]Feat: 이미지 여러장 업로드 및 미리보기

---

src/pages/WritePage/WritePageDesc/WritePageImg/WritePageImg.styles.ts
src/pages/WritePage/WritePageDesc/WritePageImg/WritePageImg.tsx

[JD-127]
이미지 삭제 불가 -> 이미지 개별 삭제 추가
[JD-127]: https://ttokttak.atlassian.net/browse/JD-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-127]feat : 이미지 개별 삭제 기능 추가

---

src/components/Modal/AlertModal/AlertModal.styles.tsx
src/components/Modal/AlertModal/AlertModal.tsx
src/pages/WritePage/WritePage.tsx
src/pages/WritePage/WritePageDesc/WritePageDesc.tsx
src/pages/WritePage/WritePageDesc/WritePageImg/WritePageImg.tsx
src/store/modalStore/modalStore.ts

[JD-63]Refactor: 중복 이미지 경고, 이미지 갯수 경고 모달
[JD-63]: https://ttokttak.atlassian.net/browse/JD-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-63]Refactor: 중복 이미지 경고, 이미지 갯수 경고 모달

---

src/App.tsx
src/pages/ChatPage/ChatPage.styles.ts
src/pages/ChatPage/ChatPage.tsx
src/pages/ChatPage/ChatPageHeader/ChatPageHeader.styles.ts
src/pages/ChatPage/ChatPageHeader/ChatPageHeader.tsx
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatPageChat.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatPageChat.tsx
src/pages/ChatPage/ChatPageMain/ChatPageMain.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageMain.tsx
src/pages/ChatPage/ChatPageMain/ChatPageUserList/ChatPageUserList.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/ChatPageUserList.tsx
src/pages/ChatPage/ChatPageMain/ChatPageUserList/ChatPageUserSearch/ChatPageUserSearch.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/ChatPageUserSearch/ChatPageUserSearch.tsx

[JD-14]feat: Chatting Page 화면 분할

[JD-14]feat: Chatting Page 화면 분할

---

src/pages/WritePage/WritePageDesc/WritePageImg/WritePageImg.tsx

[JD-63]Refactor: 업로드 이미지 미리보기 업로드 이미지 순환 시키기
[JD-63]: https://ttokttak.atlassian.net/browse/JD-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-63]Refactor: 업로드 이미지 미리보기 리팩토링

---

package-lock.json
package.json
public/mockServiceWorker.js
src/App.tsx
src/main.tsx
src/mocks/browser.ts
src/mocks/handlers.ts
src/mocks/posts.json
src/pages/PostPage/PostPage.tsx

Mocking test

---

src/App.tsx
src/components/Button/Button.tsx
src/main.tsx
src/mocks/handlers.ts
src/mocks/posts.json
src/pages/PostPage/PostPage.tsx
src/pages/PostPage/PostPageDiary/PostPageDiary.tsx
src/pages/PostPage/PostPageDiary/PostPageDiaryInfo/PostPageDiaryInfo.styles.ts
src/pages/PostPage/PostPageDiary/PostPageDiaryInfo/PostPageDiaryInfo.tsx
src/pages/WritePage/WritePageFooter/WritePageFooter.tsx

React-Query 적용

---

src/components/Modal/CommentModal/CommentFooter/CommentFooter.styles.ts
src/components/Modal/CommentModal/CommentFooter/CommentFooter.tsx
src/mocks/handlers.ts

[JD-54]Feat: 댓글 모달에서는 내 프로필로 댓글 작성 가능
[JD-54]: https://ttokttak.atlassian.net/browse/JD-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-54]Feat: 댓글 모달에서는 내 프로필로 댓글 작성 가능

---

src/components/Modal/CommentModal/CommentContent/CommentContent.tsx
src/components/Modal/CommentModal/CommentFooter/CommentFooter.tsx
src/components/Modal/CommentModal/CommentModal.tsx

[JD-54]Refactor: 댓글 모달 타입 지정
[JD-54]: https://ttokttak.atlassian.net/browse/JD-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-54]Refactor: 댓글 모달 타입 지정

---

package-lock.json
package.json
src/App.tsx
src/mocks/handlers.ts
src/pages/PostPage/PostPageHeader/PostPageEditModal/PostPageEditModal.tsx
src/pages/WritePage/WritePage.tsx
src/pages/WritePage/WritePageDesc/WritePageDesc.tsx
src/pages/WritePage/WritePageFooter/WritePageFooter.tsx
src/pages/WritePage/WritePageHeader/WritePageHeader.tsx
src/pages/WritePage/WritePageItems/WritePageItem/WritePageItem.tsx
src/pages/WritePage/WritePageItems/WritePageItems.tsx

[JD-53]: 수정하기 클릭하면 수정 페이지로 이동
[JD-53]: https://ttokttak.atlassian.net/browse/JD-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-53]: 수정하기 클릭하면 수정 페이지로 이동

---

src/components/Modal/ConfirmModal/ConfirmModal.styles.ts
src/components/Modal/ConfirmModal/ConfirmModal.tsx
src/components/layout/Layout.styles.ts
src/pages/PostPage/PostPage.styles.ts
src/pages/PostPage/PostPage.tsx
src/pages/PostPage/PostPageHeader/PostPageEditModal/PostPageEditModal.styled.ts
src/pages/PostPage/PostPageHeader/PostPageEditModal/PostPageEditModal.tsx
src/store/modalStore/modalStore.ts

[JD-178]Feat: 삭제하기 클릭 시 확인 모달 보여주기
[JD-178]: https://ttokttak.atlassian.net/browse/JD-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-178]Feat: 삭제하기 클릭 시 확인 모달 보여주기

---

src/components/Modal/CommentModal/CommentContent/CommentContent.tsx
src/pages/PostPage/PostPageDetail/PostPageDetail.styles.ts
src/pages/PostPage/PostPageDetail/PostPageDetail.tsx

[JD-13]Feat:좋아요,  댓글, DM 버튼 변경

[JD-13]Feat:좋아요,  댓글, DM 버튼 변경

---

src/components/Modal/CommentModal/CommentContent/CommentContent.tsx
src/components/Modal/CommentModal/CommentFooter/CommentFooter.tsx
src/components/Modal/CommentModal/CommentModal.styles.ts
src/components/Modal/CommentModal/CommentModal.tsx
src/pages/PostPage/PostPageDetail/PostPageDetail.tsx

[JD-54]Refactor: 댓글 인풋이 공백 문자면 댓글 등록 안됨
[JD-54]: https://ttokttak.atlassian.net/browse/JD-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-54]Refactor: 댓글 인풋이 공백 문자면 댓글 등록 안됨

---

src/components/Modal/CommentModal/CommentContent/Comment/Comment.styled.ts
src/components/Modal/CommentModal/CommentContent/Comment/Comment.tsx

[JD-55]Feat: 댓글 모달에서 댓글 마우스 호버 하면 삭제 버튼 보여주기
[JD-55]: https://ttokttak.atlassian.net/browse/JD-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-55]Feat: 댓글 모달에서 댓글 마우스 호버 하면 삭제 버튼 보여주기

---

src/components/Modal/CommentModal/CommentModal.styles.ts
src/components/Modal/CommentModal/CommentModal.tsx
src/pages/PostPage/PostPage.tsx

[JD-179]Feat:댓글창 닫기 버튼 누르면 댓글 창 닫기
[JD-179]: https://ttokttak.atlassian.net/browse/JD-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-179]Feat:댓글창 닫기 버튼 누르면 댓글 창 닫기

---

src/pages/PostPage/PostPageHeader/PostPageHeader.styles.ts
src/pages/PostPage/PostPageHeader/PostPageHeader.tsx

[JD-180]Feat: 해당 게시물이 작성된 다이어리로 이동하는 버튼
[JD-180]: https://ttokttak.atlassian.net/browse/JD-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-180]Feat: 해당 게시물이 작성된 다이어리로 이동하는 버튼

---

src/components/Modal/AlertModal/AlertModal.styles.tsx
src/pages/WritePage/WritePage.tsx
src/pages/WritePage/WritePageDesc/WritePageDesc.tsx
src/pages/WritePage/WritePageFooter/WritePageFooter.tsx
src/store/modalStore/modalStore.ts

[JD-187]Feat: 제목 입력 안하면 모달 알림 띄우기
[JD-187]: https://ttokttak.atlassian.net/browse/JD-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-187]Feat: 제목 입력 안하면 모달 알림 띄우기

---

src/pages/UserFeedPage/FeedPostsSection/FeedPostsSection.tsx
src/pages/WritePage/WritePageHeader/WritePageHeader.styles.ts
src/store/writeStore/diaryStore.ts
src/types/diaryType.ts
src/types/feedType.ts

[JD-56]Refactor: 게시글 날씨 옵션으로 변경

[JD-56]Refactor: 게시글 날씨 옵션으로 변경

---

package-lock.json
package.json
public/mockServiceWorker.js
src/App.tsx
src/components/Modal/CommentModal/CommentContent/index.tsx
src/components/Modal/CommentModal/CommentFooter/index.tsx
src/main.tsx
src/pages/PostPage/index.tsx
src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/pages/UserFeedPage/FeedPostsSection/index.tsx
src/pages/WritePage/index.tsx

[JD-9]Refactor: react-query 의존성 변경 및 import 수정

[JD-9]Refactor: react-query 의존성 변경 및 import 수정

---

src/pages/LoginPage/index.tsx
src/pages/SettingPage/index.tsx

[JD-9] Style: 로그인 페이지, 유저 정보 수정 페이지 import 문 코드 컨벤션에 맞게 수정

---

src/pages/SuggestedPage/SuggestedNavbar/index.tsx
src/pages/SuggestedPage/SuggestedPostsSection/SuggestedPost/index.tsx
src/pages/SuggestedPage/SuggestedPostsSection/index.tsx
src/pages/SuggestedPage/index.tsx

[JD-9] Style: 큰 SNS 페이지 import문 코드 컨벤션에 맞게 수정

---

src/components/layout/header/headerRightButton/index.tsx
src/components/layout/header/index.tsx
src/components/layout/index.tsx

[JD-22] Style: 헤더 import 문 코드 컨벤션에 맞게 수정

---

src/components/Modal/FollowModal/FollowList/Follow/Follow.styles.ts

[JD-37]Refactor: 팔로우, 팔로워 모달 유저 이미지 크기, font-weight 변경
[JD-37]: https://ttokttak.atlassian.net/browse/JD-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-37]Refactor: 팔로우, 팔로워 모달 UI 변경

---

src/pages/PostPage/index.tsx
src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/pages/WritePage/WritePageDesc/WritePageImg/index.tsx
src/pages/WritePage/WritePageFooter/index.tsx
src/pages/WritePage/WritePageHeader/WritePageHeader.styles.ts
src/pages/WritePage/WritePageHeader/index.tsx
src/pages/WritePage/index.tsx
src/store/imgsStore/imgsStore.ts
src/store/writeStore/diaryStore.ts
src/types/diaryType.ts

[JD-66]Feat: 게시물 작성 누르면 서버로 보내기
[JD-66]: https://ttokttak.atlassian.net/browse/JD-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-66]Feat: 게시물 작성 기능

---

src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/pages/UserFeedPage/index.tsx
src/types/userType.ts

userType 수정

---

src/hooks/usePost.ts
src/hooks/useUserFeed.ts
src/pages/PostPage/PostPageDetail/index.tsx
src/pages/PostPage/PostPageDiary/PostPageDiaryInfo/index.tsx
src/pages/PostPage/PostPageDiary/index.tsx
src/pages/PostPage/PostPageHeader/PostPageEditModal/index.tsx
src/pages/PostPage/PostPageHeader/index.tsx
src/pages/PostPage/index.tsx
src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/pages/UserFeedPage/FeedNavbar/index.tsx
src/pages/UserFeedPage/FeedPostsSection/index.tsx
src/pages/UserFeedPage/index.tsx
src/pages/WritePage/WritePageDesc/index.tsx
src/pages/WritePage/WritePageFooter/index.tsx
src/pages/WritePage/WritePageHeader/index.tsx
src/pages/WritePage/WritePageItems/WritePageItem/index.tsx
src/pages/WritePage/WritePageItems/index.tsx
src/pages/WritePage/index.tsx
src/react-query/constants.ts
src/store/imgsStore/imgsStore.ts
src/store/postStore/postStore.ts
src/types/postType.ts

react-query 모듈로 불러오기로 수정, type 이름 변경

[JD-9]Refactor: react-query, type 수정

---

src/components/Modal/CommentModal/CommentContent/Comment/Comment.styled.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/CommentReply.styled.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/index.tsx
src/components/Modal/CommentModal/CommentContent/Comment/index.tsx
src/components/Modal/CommentModal/CommentContent/CommentContent.styles.ts
src/components/Modal/CommentModal/CommentContent/index.tsx
src/components/Modal/CommentModal/CommentFooter/index.tsx
src/components/Modal/CommentModal/index.tsx
src/hooks/useComment.ts
src/hooks/useWrittenAt.ts
src/pages/PostPage/index.tsx
src/react-query/constants.ts

[JD-13]Refactor: 게시물 댓글 작성

---

src/components/Modal/ConfirmModal/index.tsx
src/hooks/usePost.ts
src/pages/PostPage/PostPageHeader/index.tsx
src/pages/PostPage/index.tsx
src/react-query/constants.ts

[JD-67]Feat: 게시글 삭제 기능 추가
[JD-67]: https://ttokttak.atlassian.net/browse/JD-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-67]Feat: 게시글 삭제 기능 추가

---

src/components/Modal/FollowModal/FollowList/Follow/Follow.styles.ts
src/components/Modal/FollowModal/FollowList/Follow/index.tsx
src/components/Modal/FollowModal/FollowList/index.tsx

[JD-12]Feat: 팔로워 모달에서 다른사람 팔로우하기
[JD-12]: https://ttokttak.atlassian.net/browse/JD-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-12]Feat: 팔로워 모달에서 다른사람 팔로우하기

---

src/components/Modal/CommentModal/CommentContent/Comment/Comment.styled.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/CommentReply.styled.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/index.tsx
src/components/Modal/CommentModal/CommentContent/Comment/index.tsx
src/components/Modal/CommentModal/CommentContent/index.tsx
src/hooks/useComment.ts
src/hooks/useWrittenAt.ts
src/pages/PostPage/PostPageDetail/index.tsx
src/react-query/constants.ts
src/types/postType.ts

[JD-13]Feat: 댓글, 대댓글 기능

---

src/components/Modal/ConfirmModal/index.tsx
src/hooks/useLoginUser.ts
src/pages/PostPage/PostPageHeader/index.tsx
src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/pages/UserFeedPage/FeedPostsSection/index.tsx
src/pages/UserFeedPage/index.tsx

[JD-9]Feat: 로그인한 유저인지 여부 확인

---

src/components/Button/Button.styles.ts
src/components/Button/index.tsx
src/components/Modal/FollowModal/FollowList/Follow/index.tsx
src/hooks/useUserFeed.ts
src/pages/UserFeedPage/FeedIntroduction/index.tsx

[JD-9]Feat: 팔로우, 팔로워 작동 로직 변경

---

src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/pages/UserFeedPage/index.tsx
src/types/userType.ts

[JD-9]Refactor: 유저 피드 수정

---

src/components/Modal/AlertModal/AlertModal.styles.tsx
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/index.tsx
src/components/Modal/CommentModal/CommentContent/index.tsx
src/components/Modal/CommentModal/CommentFooter/index.tsx
src/store/modalStore/modalStore.ts

[JD-9]Feat: 댓글, 답글 공백만 있을 때 서버로 안보내고 알림 모달

[JD-9]Feat: 댓글, 답글 공백만 있을 때 서버로 안보내고 알림 모달

---

src/App.tsx
src/pages/WritePage/WritePageFooter/index.tsx

[JD-56]Feat: 게시물 작성할 때 각각 다이어리 아이디에 따라 다른 게시물 올리기

[JD-56]Feat: 게시물 작성할 때 각각 다이어리 아이디에 따라 다른 게시물 올리기

---

src/components/Modal/CommentModal/CommentContent/Comment/index.tsx

[JD-56]Feat: 댓글 작성자한테 삭제 버튼 보여주기

[JD-56]Feat: 댓글 작성자한테 삭제 버튼 보여주기

---

src/components/Modal/CommentModal/CommentFooter/index.tsx
src/hooks/useDebounce.ts

[JD-9]Feat: useDebounce Custom Hook 생성

[JD-9]Feat: useDebounce Custom Hook 생성

---

src/hooks/usePost.ts
src/pages/WritePage/index.tsx

[JD-56]Refactor: 게시물 수정할 때 hook으로 데이터 가져오기

[JD-56]Refactor: 게시물 수정할 때 hook으로 데이터 가져오기

---

src/components/Modal/CommentModal/CommentFooter/index.tsx
src/pages/PostPage/PostPageDetail/PostDetailImgs/PostDetailImgs.styles.ts
src/pages/PostPage/PostPageDetail/PostDetailImgs/index.tsx
src/pages/PostPage/PostPageDetail/index.tsx
src/pages/PostPage/PostPageHeader/PostPageEditModal/PostPageEditModal.styled.ts
src/pages/PostPage/PostPageHeader/index.tsx
src/pages/UserFeedPage/FeedIntroduction/FeedIntroduction.styles.ts
src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/pages/UserFeedPage/FeedPostsSection/FeedPost/index.tsx
src/pages/UserFeedPage/FeedPostsSection/index.tsx
src/pages/WritePage/WritePageDesc/WritePageImg/index.tsx
src/pages/WritePage/WritePageFooter/index.tsx
src/store/imgsStore/imgsStore.ts

[JD-9]Refactor: 코드 리팩토링

---

src/components/Modal/ConfirmModal/ConfirmModal.styles.ts
src/components/Modal/ConfirmModal/index.tsx
src/pages/PostPage/index.tsx
src/pages/WritePage/WritePageDesc/WritePageImg/index.tsx
src/pages/WritePage/WritePageFooter/index.tsx
src/store/imgsStore/imgsStore.ts
src/types/postType.ts

[JD-9]Feat: 게시물 수정 기능

---

package-lock.json
package.json
src/App.tsx
src/pages/ChatPage/index.tsx
src/pages/PostPage/index.tsx
src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/pages/WritePage/WritePageFooter/index.tsx
src/utils/StompClient.ts

[JD-9]Refactor: 게시물 수정 기능

---

src/pages/PostPage/PostPageDetail/index.tsx
src/pages/WritePage/WritePageFooter/index.tsx
src/pages/WritePage/index.tsx
src/store/imgsStore/imgsStore.ts
src/store/modalStore/modalStore.ts

[JD-56]Feat: 게시글 작성, 수정할 때 이미지 0개인지 아닌지 확인

[JD-56]Feat: 게시글 작성, 수정할 때 이미지 0개인지 아닌지 확인

---

src/pages/PostPage/PostPageDetail/PostPageDetail.styles.ts
src/pages/PostPage/PostPageDetail/index.tsx

[JD-50]Feat: DM 버튼 클릭시 채팅 페이지로 이동
[JD-50]: https://ttokttak.atlassian.net/browse/JD-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-50]Feat: DM 버튼 클릭시 채팅 페이지로 이동

---

src/App.tsx
src/hooks/useChatting.ts
src/pages/ChatPage/index.tsx
src/react-query/constants.ts

[JD-14]Feat: 채팅 개인 채팅, 그룹 채팅 경로 따로 지정해서 query를 다른 이름으로 받아와 구분함

[JD-14]Feat: 채팅 개인 채팅, 그룹 채팅 경로 따로 지정해서 query를 다른 이름으로 받아와 구분함

---

src/App.tsx
src/hooks/useChatting.ts
src/pages/ChatPage/ChatPageHeader/index.tsx
src/pages/ChatPage/ChatPageMain/ChatPageChat/index.tsx
src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.tsx
src/pages/ChatPage/ChatPageMain/ChatPageUserList/ChatPageUserList.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/ChatPageUserSearch/ChatPageUserSearch.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/index.tsx
src/pages/ChatPage/ChatPageMain/index.tsx
src/pages/ChatPage/index.tsx
src/pages/PostPage/PostPageDetail/index.tsx
src/pages/UserFeedPage/FeedIntroduction/index.tsx
src/react-query/constants.ts
src/types/chattingType.ts

[JD-14]Feat: 채팅 목록 가져오기

---

src/hooks/useChatting.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatMessage.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatMessage.tsx
src/pages/ChatPage/ChatPageMain/ChatPageChat/index.tsx
src/pages/ChatPage/ChatPageMain/index.tsx
src/pages/ChatPage/index.tsx
src/types/chattingType.ts

[JD-14]Refactor: 내가 보낸 채팅 다른사람이 보내는 채팅 구분해서 보여주기

[JD-14]Refactor: 내가 보낸 채팅 다른사람이 보내는 채팅 구분해서 보여주기

---

src/hooks/useLoginUser.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatMessage.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatMessage.tsx
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatPageChat.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/index.tsx
src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.tsx
src/pages/ChatPage/ChatPageMain/index.tsx
src/pages/ChatPage/index.tsx
src/pages/PostPage/PostPageHeader/PostPageHeader.styles.ts
src/pages/UserFeedPage/FeedIntroduction/FeedIntroduction.styles.ts
src/pages/UserFeedPage/index.tsx
src/react-query/constants.ts
src/store/userStore/userStore.ts

[JD-14]Feat: 채팅창 입장시 스크롤 맨 아래로 내려가게 하기

[JD-14]Feat: 채팅창 입장시 스크롤 맨 아래로 내려가게 하기

---

package-lock.json
package.json

package.json 추가

---

src/components/Modal/CommentModal/CommentContent/Comment/Comment.styles.ts
src/components/Modal/CommentModal/CommentFooter/CommentFooter.styles.ts
src/components/Modal/CommentModal/CommentFooter/index.tsx

[JD-9]Refactor: 멘션기능 리팩토링

---

src/hooks/useChatting.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatMessage.tsx
src/pages/ChatPage/ChatPageMain/ChatPageChat/index.tsx
src/pages/ChatPage/ChatPageMain/index.tsx
src/pages/ChatPage/index.tsx
src/types/chattingType.ts

[JD-9]Feat: Intersection Observer 추가

[JD-9]Feat: Intersection Observer 추가

---

package-lock.json
package.json
src/hooks/useChatting.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatMessage.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatMessage.tsx
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatPageChat.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/index.tsx

[JD-13]Feat: 역방향 무한 스크롤

---

src/hooks/useChatting.ts
src/hooks/usePost.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.tsx
src/pages/ChatPage/index.tsx
src/pages/PostPage/PostPageHeader/PostPageHeader.styles.ts
src/pages/WritePage/WritePageHeader/WritePageHeader.styles.ts
src/pages/WritePage/WritePageHeader/index.tsx

[JD-14]Refactor: 채팅 페이지 리팩토링

---

src/components/Modal/CommentModal/CommentFooter/CommentFooter.styles.ts
src/components/Modal/CommentModal/CommentFooter/defaultStyle.ts
src/components/Modal/CommentModal/CommentFooter/index.tsx
src/hooks/useComment.ts
src/store/tagStore/tagStore.ts

[JD-13]Feat: react-metions

---

src/components/Modal/CommentModal/CommentContent/Comment/CommentDeleteModal.styles.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/CommentReply.styled.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/defaultStyle.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/index.tsx

[JD-13]Feat: 답글 멘션 기능 추가

---

src/pages/ChatPage/ChatPageMain/ChatPageChat/index.tsx
src/pages/ChatPage/ChatPageMain/ChatPageUserList/index.tsx

[JD-14]Feat: 채팅 리스트 마지막 메세지 시간 순 정렬

[JD-14]Feat: 채팅 리스트 마지막 메세지 시간 순 정렬

---

src/components/Modal/CommentModal/CommentFooter/index.tsx
src/pages/ChatPage/ChatPageHeader/ChatPageHeader.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageChat/ChatMessage.tsx
src/pages/ChatPage/ChatPageMain/ChatPageChat/index.tsx
src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.tsx
src/pages/ChatPage/ChatPageMain/ChatPageUserList/index.tsx
src/pages/ChatPage/ChatPageMain/index.tsx
src/pages/ChatPage/index.tsx
src/store/chattingStore/chattingStore.ts
src/types/chattingType.ts

[JD-14]Refactor: 채팅 상태 변경

---

src/components/Modal/CommentModal/CommentContent/CommentContent.styles.ts
src/components/Modal/CommentModal/CommentContent/index.tsx
src/components/Modal/CommentModal/CommentFooter/index.tsx
src/components/Modal/MentionModal/MentionModal.styles.ts
src/components/Modal/MentionModal/index.tsx
src/hooks/usePost.ts

[JD-14]Refactor: 멘션 리팩토링

---

src/api/index.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/CommentReply.styled.ts
src/components/Modal/CommentModal/CommentContent/Comment/CommentReply/Reply.tsx
src/components/Modal/CommentModal/CommentContent/Comment/index.tsx
src/components/Modal/CommentModal/CommentFooter/defaultStyle.ts

[JD-13]Feat: 게시물 댓글, 답글 멘션된 사용자 텍스트 컬러 변경

[JD-13]Feat: 게시물 댓글, 답글 멘션된 사용자 텍스트 컬러 변경

---

src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.tsx

DM 페이지에서 다이어리 채팅방인 경우 채팅방 이름 색상 변경

[JD-153]Refactor: DM 페이지 채팅 이름 색상 변경

---

src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.styles.ts
src/pages/ChatPage/ChatPageMain/ChatPageUserList/Chat.tsx

[JD-153]Refactor: 채팅 목록 그룹채팅방일 경우 그룹 표시 아이콘 생성
[JD-153]: https://ttokttak.atlassian.net/browse/JD-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[JD-153]Refactor: 채팅 목록 그룹채팅방일 경우 그룹 표시 아이콘 생성
